language: node_js
sudo: false
before_script:
  - npm install $ICONV
env:
  - CXX=g++-4.8
jobs:
  include:
  - node_js: "0.10"
    env: ICONV="iconv@~2.1.11"
  - node_js: "0.12"
    env: ICONV="iconv@~2.1.11"
  - node_js: "4"
    env: ICONV="iconv@~2.1.11"
  - node_js: "6"
    env: ICONV="iconv@~2.2.0"
  - node_js: "8"
    env: ICONV="iconv@~2.3.0"
  - node_js: "10"
    env: ICONV="iconv@~3.0.0"
  - node_js: "12"
    env: ICONV="iconv@~3.0.0"
  - node_js: "14"
    env: ICONV="iconv@~3.0.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email:
    - andris@kreata.ee
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ed18fd9b3e529b3c2cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
